auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from models import db
from models.user import User

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        name= request.form['name']
        email = request.form['email']
        location = request.form['location']
        interests = request.form['interests']
        can_relocate = request.form.get('can_relocate') == '1' #only true or false
        username = request.form['username']
         
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif not (name and email and location and interests):
            error = "Please fill in all fields"

        if error is None:
            try:
                new_user = User(
                    name=name,
                    email=email,
                    location=location,
                    interests=interests,
                    can_relocate=can_relocate,
                    username=username,
                    password=generate_password_hash(password)
                )
                db.session.add(new_user)
                db.session.commit()
                flash('Registration successful. Please log in.')
                return redirect(url_for('auth.login'))
            except Exception as e:
                db.session.rollback()
                error = f"User {username} is already registered."
                flash(error)

        flash(error)

    return render_template('auth/register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        # SQLAlchemy query to get the user by username
        user = User.query.filter_by(username=username).first()
        

        if user is None:
            error = 'Incorrect username.'

        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))
        if error is not None:
            flash(error)
            print(f"Login error: {error}")
        flash(error)

    return render_template('auth/login.html')


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout')
def logout():
    session.clear()
    flash('You have been logged out')
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Pathway App{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
  <!-- navbar-light bg-light -->
    <nav class="navbar navbar-expand-lg bg-dark fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('index') }}" style="color: white;">Something App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      
          <div class="collapse navbar-collapse " id="navbarNav">
            <ul class="navbar-nav ms-auto">
              {% if session['user_id'] %}
                <li class="nav-item">
                  <a class="nav-link" href="#">Hello, {{ session['username'] }}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.Logout') }}" style="color: white;">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.login') }}" style="color: white;">Login</a>
                </li>
                <li class="nav-item ">
                  <a class="nav-link" href="{{ url_for('auth.register') }}" style="color: white;">Register</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      

    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<section>
    <section class="bg-dark text-light py-5 text-center full-width-banner">
        <h1 class="display-4">Do you have what it takes?</h1>
        <p class="lead">Take some aptitude tests to find out and more.</p>
    </section>
    
<section>
<div class="container mt-5">
    <div class="row">
        {% for card in cards %}
        <div class="col-md-4 mb-4">
            <div class="custom-card h-100 d-flex flex-column">
                <div class="card-img-top" 
                     style="background-image: url('{{ url_for("static", filename=card.image) }}');">
                </div>
                <div class="p-3 flex-grow-1 d-flex flex-column align-items-center">
                    <h3 class="mb-0 fw-bold">{{ card.title }}</h3><br>
                    <h5 class="mb-0">{{ card.description }}</h5>
                </div>
                <div class="card-footer d-flex justify-content-between align-items-center px-3 py-2">
                    <a href={{ card.link }}><span class="fw-bold links read-more">Read More</span></a>
                </div>

<!-- <div class="card-footer d-flex justify-content-between align-items-center px-3 py-2">
                    {% if g.user %}
                        <a href="{{ card.link }}"><span class="fw-bold links read-more">Read More</span></a>
                    {% else %}
                        <span class="text-muted">Login to read more</span>
                    {% endif %}
                </div> -->

            </div>
        </div>
        {% endfor %}
    </div>
</div>
</section>
{% endblock %}